### ISSUE TITLE
Ratio and size

### ISSUE THREAD

**Issue by raphaelbastide** [celiadzc/type-derivation#1]
Try to find a good balance between `ratio` and `size` to get an optimal scrollable image.
https://github.com/celiadzc/type-derivation/blob/master/type-derivation.dot#L4-L5

**Comment by celiadzc** [comment]
It's done. I can't push it because i've created a conflict in the branch... I've searched how to resolve this but it doesn't work so we'll see this on friday.

**Comment by raphaelbastide** [comment]
Ok see you on friday!

**Comment by raphaelbastide** [comment]
In case you want to give it a new try: https://www.youtube.com/watch?v=plm4x_DjDa8

**Comment by celiadzc** [comment]
I did it, I hope that everything is alright!

**Comment by celiadzc** [comment]
Anyway, this is my commit on style test : https://github.com/celiadzc/type-derivation/commit/74916e2cee782269c7df97676b04af08cb7fd3c2
I played with ratio, size and nodesep to make it more comfortable. 
You can take a look here :
![cap](https://cloud.githubusercontent.com/assets/9606433/13794436/0678cb82-eafc-11e5-9c3c-fc4105e30987.jpg)

**Comment by raphaelbastide** [comment]
I can’t see the difference with the version I committed before.

**Comment by raphaelbastide** [comment]
After a quick check, the files ’type-derivation.dot’ I created and `type-derivation` you created are totally similar. I will remove yours to keep the `.dot` extention.

**Comment by celiadzc** [comment]
Because I think that I erased yours in committing. I'm clearly not happy to say that.[ A part of your edit ](https://github.com/celiadzc/type-derivation/commit/6459ab51df1afd50685106f3c527708684f3c81d)with a look :
![apercu-edit-raphael](https://cloud.githubusercontent.com/assets/9606433/13819270/3e4f1212-eb99-11e5-8d95-b6e2fd4e6e81.jpg)

Maybe what I've done was not what you asked for.

**Comment by raphaelbastide** [comment]
You didn’t make anything wrong. The good thing with git is that you can always get things back from old version.

About the structure, I ask a question on StackOverflow. http://stackoverflow.com/questions/36041176/restrict-graph-to-a-specific-format

**Comment by celiadzc** [comment]
Ok I'll check it. 
I tried monday to fix a size to the viz with page settings but it doesn't work. I'll do it again.
I found some nice style [on this page](http://4webmaster.de/wiki/Graphviz-Tutorial#ratio).

**Comment by raphaelbastide** [comment]
>  I found some nice style on this page. 

Great resource, thanks.

**Comment by celiadzc** [comment]
Ok so now, the graph is settled in portrait. But indications of forks types are eaten by the ratio in the flow.
