### ISSUE TITLE
How to serve

### ISSUE THREAD

**Issue by raphaelbastide** [celiadzc/type-derivation#3]
- Download and install [Xampp](https://www.apachefriends.org/index.html)
- Change the default directory to serve in the Xampp preferences, set it to your project’s directory
- Once you can access to `localhost` in your web browser, open something like `localhost/viewer/`

**Comment by raphaelbastide** [comment]
Did you managed to do that? @celiadzc

**Comment by celiadzc** [comment]
I've got no time for now, Corpus takes it. This is why I started with the simplest instructions.
