### ISSUE TITLE
Translate README

### ISSUE THREAD

**Issue by raphaelbastide** [celiadzc/type-derivation#5]

**Comment by celiadzc** [comment]
✔ done

**Comment by celiadzc** [comment]
Before commit it, I show you the translation : 

# Type Derivation

Try to make visual mapping of typography derivations on Open Font Licence. The project was initied by Célia Deyzac in the typesetting course of [Raphaël Bastide](http://www.raphaelbastide.com/) in [ESADHaR](http://esadhar.fr/). 

### Tools

Map made with [GraphViz](http://graphviz.org/) software.

### Use

Launch a web server, as node or apache (mamp, wamp..) then access to index.html via localhost in the browser. 

### Collaboration

This project is non-exhaustive and open to collaborations. 

## Thanks

Graphviz to HTML and SVG conversion possible thanks to [Viz](https://github.com/mdaines/viz.js)

**Comment by raphaelbastide** [comment]
Just commit it, I’ll correct it directly on the file if needed :)
