### ISSUE TITLE
Add a description

### ISSUE THREAD

**Issue by raphaelbastide** [celiadzc/type-derivation#6]
![selection_035](https://cloud.githubusercontent.com/assets/193122/13680027/fd9fa7be-e6f6-11e5-93f1-690e9bd16fe0.png)

**Comment by celiadzc** [comment]
✔ done

**Comment by raphaelbastide** [comment]
I suggest:  
A visualization of typefaces derivation workflows
or  
Visualization of open source typography derivations

What do you think?

**Comment by celiadzc** [comment]
I think that the second one is better, more keywords you know... Moreover "workflow" word can afraid people.

**Comment by raphaelbastide** [comment]
Allright. I close this issue. Don’t forget to replace the description.
